# Generated by Django 5.1.1 on 2024-09-30 09:56

import datetime
import django_jalali.db.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('user_phone', models.CharField(max_length=15, unique=True, verbose_name='شماره موبایل')),
                ('image', models.ImageField(blank=True, null=True, upload_to='users/avatar/')),
                ('name', models.CharField(max_length=1000, verbose_name='نام')),
                ('family', models.CharField(blank=True, max_length=50, null=True, verbose_name='نام خانوادگی')),
                ('register_date', django_jalali.db.models.jDateField(default=datetime.date(2024, 9, 30), verbose_name='تاریخ ثبت نام')),
                ('is_active', models.BooleanField(default=False, verbose_name='کاربر فعال باشد یا نه؟')),
                ('is_admin', models.BooleanField(default=False, verbose_name='کاربر مدیر باشد یا نه؟')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'کاربر',
                'verbose_name_plural': 'کاربران',
            },
        ),
    ]
