# Generated by Django 5.1.1 on 2024-09-30 12:50

import ckeditor.fields
import ckeditor_uploader.fields
import datetime
import django.db.models.deletion
import django_jalali.db.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=1000, verbose_name='نام محصول')),
                ('product_cover', models.ImageField(upload_to='products/product_covers/', verbose_name='کاور محصول')),
                ('product_cover_alt', models.CharField(max_length=100, verbose_name='متن جایگزین کاور')),
                ('product_cover_title', models.CharField(max_length=100, verbose_name='عنوان کاور')),
                ('slug', models.SlugField(unique=True, verbose_name='عنوان در آدرس')),
                ('short_description', ckeditor.fields.RichTextField(verbose_name='توضیحات اجمالی')),
                ('long_description', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='توضیحات کامل')),
                ('view_count', models.PositiveIntegerField(default=1)),
                ('created_at', django_jalali.db.models.jDateField(default=datetime.date(2024, 9, 30), verbose_name='تاریخ ثبت محصول')),
                ('updated_at', django_jalali.db.models.jDateField(blank=True, null=True, verbose_name='تاریخ آخرین بروزرسانی')),
                ('is_active', models.BooleanField(default=False, verbose_name='وضعیت محصول : (فعال/غیرفعال)')),
            ],
            options={
                'verbose_name': 'محصول',
                'verbose_name_plural': 'محصولات',
            },
        ),
        migrations.CreateModel(
            name='ProductInventoryUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_name', models.CharField(max_length=100, verbose_name='واحد شمارش')),
            ],
            options={
                'verbose_name': 'واحد اندازه گیری',
                'verbose_name_plural': 'واحدهای اندازه گیری',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=1000, verbose_name='نام دسته بندی')),
                ('slug', models.SlugField(unique=True, verbose_name='عنوان در آدرس')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='categories/logos/', verbose_name='لوگو')),
                ('logo_alt', models.CharField(blank=True, max_length=1000, null=True, verbose_name='متن جایگزین لوگو')),
                ('logo_title', models.CharField(blank=True, max_length=1000, null=True, verbose_name='عنوان لوگو')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='product.category', verbose_name='دسته بندی والد')),
            ],
            options={
                'verbose_name': 'دسته بندی',
                'verbose_name_plural': 'دسته بندی ها',
            },
        ),
        migrations.CreateModel(
            name='ProductAttribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attribute_value', models.CharField(max_length=1000, verbose_name='مقدار ویژگی')),
                ('attribute_name', models.CharField(max_length=300, verbose_name='نام ویژگی')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productAttr_of_product', to='product.product', verbose_name='محصول')),
            ],
            options={
                'verbose_name': 'ویژگی محصول',
                'verbose_name_plural': 'ویژگی محصولات',
            },
        ),
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_of_products', to='product.category', verbose_name='دسته بندی')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productCategory_of_product', to='product.product', verbose_name='محصول')),
            ],
            options={
                'verbose_name': 'دسته بندی محصول',
                'verbose_name_plural': 'دسته بندی محصولات',
            },
        ),
        migrations.CreateModel(
            name='ProductGallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='marketplace/products/galleries/', verbose_name='تصویر')),
                ('alt_image', models.CharField(max_length=255, verbose_name='متن جایگزین')),
                ('title_image', models.CharField(max_length=255, verbose_name='عنوان')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='galleries', to='product.product', verbose_name='محصول')),
            ],
            options={
                'verbose_name': 'گالری محصول فروشگاه',
                'verbose_name_plural': 'گالری محصولات فروشگاه',
            },
        ),
        migrations.CreateModel(
            name='ProductInventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=10, verbose_name='تعداد محصول')),
                ('product_sales_price', models.PositiveIntegerField(blank=True, null=True, verbose_name='قیمت فروش محصول')),
                ('discount_percent', models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='درصد تخفیف')),
                ('created_at', django_jalali.db.models.jDateField(default=datetime.date(2024, 9, 30), verbose_name='تاریخ ثبت انبار')),
                ('final_price', models.PositiveIntegerField(blank=True, help_text='این فیلد توسط سیستم پر میشود', null=True, verbose_name='قیمت نهایی')),
                ('product_lable', models.CharField(default='', max_length=500, verbose_name='نام محصول در انبار')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_of_inventory', to='product.product', verbose_name='محصول')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unit_of_inventory', to='product.productinventoryunit', verbose_name='واحد شمارش')),
            ],
            options={
                'verbose_name': 'انبار محصول فروشنده',
                'verbose_name_plural': ' انبار محصولات فروشندگان',
            },
        ),
        migrations.CreateModel(
            name='ProductSeo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=6000, verbose_name='عنوان')),
                ('content', models.TextField(verbose_name='محتوا')),
                ('type', models.CharField(choices=[('name', 'name'), ('property', 'property')], max_length=1000, verbose_name='نوع متا تگ')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productSeo_of_product', to='product.product', verbose_name='محصول')),
            ],
            options={
                'verbose_name': 'سئو محصول',
                'verbose_name_plural': 'سئو محصولات',
            },
        ),
        migrations.CreateModel(
            name='ProductTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_title', models.CharField(max_length=1000, verbose_name='عنوان تگ')),
                ('slug', models.SlugField(unique=True, verbose_name='عنوان در نوار آدرس')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productTag_of_product', to='product.product', verbose_name='محصول')),
            ],
            options={
                'verbose_name': 'تگ محصول',
                'verbose_name_plural': 'تگهای محصول',
            },
        ),
        migrations.CreateModel(
            name='ProductTimingDiscount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', django_jalali.db.models.jDateField(verbose_name='تاریخ شروع تخفیف')),
                ('day_count', models.IntegerField(verbose_name='تعداد روز تخفیف')),
                ('end_time', django_jalali.db.models.jDateField(blank=True, help_text='این گزینه توسط سیستم پر میشود', null=True, verbose_name='تاریخ پایان')),
                ('discount', models.IntegerField(verbose_name='درصد تخفیف')),
                ('final_price', models.IntegerField(blank=True, null=True, verbose_name='قیمت نهایی')),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='product_timing_discount', to='product.product', verbose_name='محصول')),
                ('product_inventory', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_timing_discount', to='product.productinventory', verbose_name='انبار محصول')),
            ],
            options={
                'verbose_name': 'تخفیف مدت دار',
                'verbose_name_plural': 'تخفیف های مدت دار',
            },
        ),
    ]
