# Generated by Django 5.1.1 on 2024-09-30 13:09

import datetime
import django.db.models.deletion
import django_jalali.db.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productinventory',
            options={'verbose_name': 'انبار محصول ', 'verbose_name_plural': ' انبار محصولات '},
        ),
        migrations.CreateModel(
            name='ProductComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(verbose_name='متن نظر')),
                ('is_active', models.BooleanField(default=False, verbose_name='وضعیت نظر : (فعال/غیرفعال)')),
                ('created_at', django_jalali.db.models.jDateField(default=datetime.date(2024, 9, 30), verbose_name='تاریخ ثبت محصول')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='market_product_comments', to='product.product', verbose_name='محصول')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'نظر محصول',
                'verbose_name_plural': 'نضرات محصولات',
            },
        ),
        migrations.CreateModel(
            name='ProductStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.IntegerField(default=0, verbose_name='امتیاز')),
                ('like', models.IntegerField(default=0, verbose_name='پسند شد')),
                ('dis_like', models.IntegerField(default=0, verbose_name='پسند نشد')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_status', to='product.product', verbose_name='محصول')),
            ],
            options={
                'verbose_name': 'لایک - امتیاز محصول',
                'verbose_name_plural': 'لایک ها - امتیازهای محصول',
            },
        ),
    ]
