# Generated by Django 5.1.1 on 2024-10-09 07:49

import datetime
import django_jalali.db.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_alter_productinventory_options_productcomment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='created_at',
            field=django_jalali.db.models.jDateField(default=datetime.date(2024, 10, 9), verbose_name='تاریخ ثبت محصول'),
        ),
        migrations.AlterField(
            model_name='productcomment',
            name='created_at',
            field=django_jalali.db.models.jDateField(default=datetime.date(2024, 10, 9), verbose_name='تاریخ ثبت محصول'),
        ),
        migrations.AlterField(
            model_name='productinventory',
            name='created_at',
            field=django_jalali.db.models.jDateField(default=datetime.date(2024, 10, 9), verbose_name='تاریخ ثبت انبار'),
        ),
    ]
