# Generated by Django 5.1.1 on 2024-09-30 13:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product', '0002_alter_productinventory_options_productcomment_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='وضعیت (فعال/غیرفعال)')),
                ('title', models.CharField(max_length=5000, verbose_name='عنوان لیست')),
                ('list_location', models.CharField(choices=[('top_top', 'بالا - بالا'), ('top_center', 'بالا - وسط'), ('top_bottom', 'بالا - پایین'), ('center_top', 'وسط - بالا'), ('center_center', 'وسط - وسط'), ('center_bottom', 'وسط - پایین'), ('bottom_top', 'پایین - بالا'), ('bottom_center', 'پایین - وسط'), ('bottom_bottom', 'پایین - پایین')], max_length=500, verbose_name='محل قرار گرفتن')),
                ('auto_play', models.BooleanField(default=False, verbose_name='شروع خودکار')),
            ],
            options={
                'verbose_name': 'لیست افقی دسته',
                'verbose_name_plural': 'لیستهای افقی دسته ها',
            },
        ),
        migrations.CreateModel(
            name='ProductList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=5000, verbose_name='عنوان لیست')),
                ('list_location', models.CharField(choices=[('top_top', 'بالا - بالا'), ('top_center', 'بالا - وسط'), ('top_bottom', 'بالا - پایین'), ('center_top', 'وسط - بالا'), ('center_center', 'وسط - وسط'), ('center_bottom', 'وسط - پایین'), ('bottom_top', 'پایین - بالا'), ('bottom_center', 'پایین - وسط'), ('bottom_bottom', 'پایین - پایین')], max_length=500, verbose_name='محل قرار گرفتن')),
                ('auto_play', models.BooleanField(default=False, verbose_name='شروع خودکار')),
                ('is_active', models.BooleanField(default=True, verbose_name='وضعیت (فعال/غیرفعال)')),
            ],
            options={
                'verbose_name': 'لیست افقی محصول',
                'verbose_name_plural': 'لیستهای افقی محصولات',
            },
        ),
        migrations.CreateModel(
            name='CategoryListItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='وضعیت (فعال/غیرفعال)')),
                ('link', models.URLField(blank=True, null=True, verbose_name='لینک(اختیاری)')),
                ('title', models.CharField(blank=True, max_length=5000, null=True, verbose_name='عنوان آیتم(اختیاری)')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category', to='product.category', verbose_name='دسته بندی')),
                ('list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_list_item', to='horizonta_lists.categorylist', verbose_name='لیست')),
            ],
            options={
                'verbose_name': 'آیتم لیست افقی دسته ',
                'verbose_name_plural': ' آیتم لیست افقی دسته ها',
            },
        ),
        migrations.CreateModel(
            name='ProductListItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='وضعیت (فعال/غیرفعال)')),
                ('link', models.URLField(blank=True, null=True, verbose_name='لینک(اختیاری)')),
                ('title', models.CharField(blank=True, max_length=5000, null=True, verbose_name='عنوان آیتم(اختیاری)')),
                ('list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_list_item', to='horizonta_lists.productlist', verbose_name='لیست')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='product.product', verbose_name='محصول')),
            ],
            options={
                'verbose_name': 'آیتم لیست افقی محصول',
                'verbose_name_plural': ' آیتم لیست افقی محصولات',
            },
        ),
    ]
