# Generated by Django 5.1.1 on 2024-09-30 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0002_delete_menu'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sitetemplate',
            options={'verbose_name': 'تم', 'verbose_name_plural': 'تم ها'},
        ),
        migrations.AddField(
            model_name='sitetemplate',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='themes/', verbose_name='عکس'),
        ),
    ]
