# Generated by Django 5.1.1 on 2024-09-30 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0003_alter_sitetemplate_options_sitetemplate_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='footerlink',
            options={'verbose_name': 'لینک  فوتر', 'verbose_name_plural': 'لینک های فوتر'},
        ),
        migrations.AlterModelOptions(
            name='footersettings',
            options={'verbose_name': 'تنظیم فوتر', 'verbose_name_plural': 'تنظیمات فوتر'},
        ),
        migrations.AlterModelOptions(
            name='headersettings',
            options={'verbose_name': 'تنظیم سربرگ', 'verbose_name_plural': 'تنظیمات سربرگ'},
        ),
        migrations.AlterModelOptions(
            name='metaheader',
            options={'verbose_name': 'سئو سربرگ', 'verbose_name_plural': 'سئو سربرگ'},
        ),
        migrations.AlterModelOptions(
            name='sociallink',
            options={'verbose_name': 'شبکه اجتماعی', 'verbose_name_plural': 'شبکه های اجتماعی'},
        ),
        migrations.AddField(
            model_name='sitetemplate',
            name='title',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='عنوان تم'),
        ),
    ]
