# Generated by Django 5.1.1 on 2024-10-09 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banner', '0002_alter_banner_register_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='badge1',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='تیکه متن 1'),
        ),
        migrations.AddField(
            model_name='banner',
            name='badge2',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='تیکه متن 2'),
        ),
        migrations.AddField(
            model_name='banner',
            name='badge3',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='تیکه متن 3'),
        ),
    ]
