# Generated by Django 5.1.1 on 2024-10-09 13:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banner', '0003_banner_badge1_banner_badge2_banner_badge3'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='banner',
            name='css_class',
        ),
        migrations.RemoveField(
            model_name='banner',
            name='css_style',
        ),
        migrations.CreateModel(
            name='BannerSize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(choices=[('col-sm-1', '8.33% درحالت گوشی'), ('col-sm-2', '16.66% درحالت گوشی'), ('col-sm-3', '24.99% درحالت گوشی'), ('col-sm-4', '33.32% درحالت گوشی'), ('col-sm-5', '41.65% درحالت گوشی'), ('col-sm-6', '49.98% درحالت گوشی'), ('col-sm-7', '58.31% درحالت گوشی'), ('col-sm-8', '66.64% درحالت گوشی'), ('col-sm-9', '74.97% درحالت گوشی'), ('col-sm-10', '83.3% درحالت گوشی'), ('col-sm-11', '91.63% درحالت گوشی'), ('col-sm-12', '100% درحالت گوشی'), ('col-md-1', '8.33% درحالت تبلت'), ('col-md-2', '16.66% درحالت تبلت'), ('col-md-3', '24.99% درحالت تبلت'), ('col-md-4', '33.32% درحالت تبلت'), ('col-md-5', '41.65% درحالت تبلت'), ('col-md-6', '49.98% درحالت تبلت'), ('col-md-7', '58.31% درحالت تبلت'), ('col-md-8', '66.64% درحالت تبلت'), ('col-md-9', '74.97% درحالت تبلت'), ('col-md-10', '83.3% درحالت تبلت'), ('col-md-11', '91.63% درحالت تبلت'), ('col-md-12', '100% درحالت تبلت'), ('col-lg-1', '8.33% درحالت مانیتور'), ('col-lg-2', '16.66% درحالت مانیتور'), ('col-lg-3', '24.99% درحالت مانیتور'), ('col-lg-4', '33.32% درحالت مانیتور'), ('col-lg-5', '41.65% درحالت مانیتور'), ('col-lg-6', '49.98% درحالت مانیتور'), ('col-lg-7', '58.31% درحالت مانیتور'), ('col-lg-8', '66.64% درحالت مانیتور'), ('col-lg-9', '74.97% درحالت مانیتور'), ('col-lg-10', '83.3% درحالت مانیتور'), ('col-lg-11', '91.63% درحالت مانیتور'), ('col-lg-12', '100% درحالت مانیتور')], max_length=255, verbose_name='اندازه')),
                ('banner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='banner.banner', verbose_name='انتخاب بنر')),
            ],
        ),
    ]
