# Generated by Django 5.1.1 on 2024-10-09 13:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banner', '0004_remove_banner_css_class_remove_banner_css_style_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bannersize',
            name='banner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='banner_size', to='banner.banner', verbose_name='انتخاب بنر'),
        ),
    ]
