# Generated by Django 5.1.1 on 2024-09-30 12:21

import datetime
import django.db.models.deletion
import django_jalali.db.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=250, null=True, verbose_name='عنوان اسلایدر')),
                ('register_date', django_jalali.db.models.jDateField(default=datetime.date(2024, 9, 30), verbose_name='تاریخ ساخت')),
                ('delay', models.IntegerField(blank=True, null=True, verbose_name='مدت زمان تعویض')),
                ('auto_play', models.BooleanField(default=True, verbose_name='شروع خودکار')),
                ('type', models.CharField(choices=[('top_top', 'بالا - بالا'), ('top_center', 'بالا - وسط'), ('top_bottom', 'بالا - پایین'), ('center_top', 'وسط - بالا'), ('center_center', 'وسط - وسط'), ('center_bottom', 'وسط - پایین'), ('bottom_top', 'پایین - بالا'), ('bottom_center', 'پایین - وسط'), ('bottom_bottom', 'پایین - پایین')], default='top_top', max_length=250, verbose_name='مکان نمایش')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال / غیرفعال')),
            ],
            options={
                'verbose_name': 'اسلایدر',
                'verbose_name_plural': 'اسلایدرها',
            },
        ),
        migrations.CreateModel(
            name='SliderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=250, null=True, verbose_name='عنوان اسلایدر')),
                ('description', models.TextField(blank=True, null=True, verbose_name='توضیحات اسلایدر')),
                ('link', models.URLField(blank=True, max_length=600, null=True, verbose_name='لینک')),
                ('link_title', models.CharField(blank=True, max_length=250, null=True, verbose_name='عنوان لینک')),
                ('picture', models.ImageField(upload_to='sliders/', verbose_name='عکس اسلایدر')),
                ('picture_alt', models.CharField(blank=True, max_length=250, null=True, verbose_name='متن جایگزین')),
                ('picture_title', models.CharField(blank=True, max_length=250, null=True, verbose_name='عنوان تصویر')),
                ('width', models.IntegerField(blank=True, null=True, verbose_name='عرض تصویر')),
                ('height', models.IntegerField(blank=True, null=True, verbose_name='ارتفاع تصوبر')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال / غیرفعال')),
                ('register_date', django_jalali.db.models.jDateField(default=datetime.date(2024, 9, 30), verbose_name='تاریخ ساخت')),
                ('slider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slider_items', to='slider.slider', verbose_name='اسلایدر')),
            ],
            options={
                'verbose_name': 'آیتم اسلایدر',
                'verbose_name_plural': 'آیتم اسلایدر ها',
            },
        ),
    ]
